java_library(
    name = "server",
    srcs = glob(["**/*.java"]),
    deps = [
        "//java/com/google/cloud/cache/apps/loadtest:server",
        "//java/com/google/common/base",
        "//java/com/google/common/collect",
        "//java/com/google/common/primitives",
        "//third_party/java/appengine:appengine-api",
        "//third_party/java/servlet/servlet_api",
    ],
)
